name: Build

on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'src-tauri/**/*'
      - 'src/**/*'
      - 'package.json'
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - 'src-tauri/**/*'
      - 'src/**/*'
      - 'package.json'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Set HASH env variable as the latest git hash
        run: $HASH=$(git rev-parse --short HEAD)

      - name: Install deps and build
        run: yarn && yarn tauri build

      - name: Zip build
        run: 7z a -tzip remitm_windows.zip src-tauri/target/release/remitm.exe src-tauri/target/release/lang/

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: remitm_windows_portable
          path: remitm_windows.zip

      - name: Upload bundle
        uses: actions/upload-artifact@v3
        with:
          name: remitm_windows_bundle
          path: src-tauri/target/release/bundle/msi/*.msi

  build-ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install libraries
        run: sudo apt install libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Install deps and build
        run: HASH=$(git rev-parse --short HEAD) yarn && yarn tauri build

      - name: compress build
        run: tar -czvf remitm_linux.tar.gz src-tauri/target/release/remitm src-tauri/target/release/lang/

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: remitm_linux_portable
          path: remitm_linux.tar.gz

      - name: Upload bundle
        uses: actions/upload-artifact@v3
        with:
          name: remitm_linux_bundle
          path: src-tauri/target/release/bundle/deb/remitm.deb

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Set HASH env variable as the latest git hash
        run: export HASH=$(git rev-parse --short HEAD)

      - name: Install deps and build
        run: yarn && yarn tauri build

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: remitm_mac
          path: src-tauri/target/release/bundle/dmg/remitm.dmg
